spring:
  application:
    name: genergy-eam-grpc-server
  profiles:
    active: dev

grpc:
  server:
    port: 7002

logging:
  level:
    net.gichain.genergy.eam.grpc.server: debug
  file:
    path: ./logs/
  pattern:
    console: '%d{yyyy/MM/dd} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy/MM/dd} [%thread] %-5level %logger{50} - %msg%n'

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

---
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: genergy_eam
    url: jdbc:mysql://172.18.10.78:3306/genergy_eam?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: root
    password: 6x@test2018

devtools:
  restart:
    enabled: true
    additional-paths: src/main/java